[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "cms"
source = "apps/cms"

[[services]]
name = "web"
source = "apps/web"

[[services]]
name = "postgres"